apiVersion: apps/v1
kind: Deployment
metadata:
  name: hadoop-operator
spec:
  replicas: 2
  selector:
    matchLabels:
      name: hadoop-operator
  template:
    metadata:
      labels:
        name: hadoop-operator
    spec:
      serviceAccountName: hadoop-operator
      containers:
        - name: hadoop-operator
          # Replace this with the built image name
          image: alicek106/hadoop:2.6.0-operator
          command:
          - hadoop-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "hadoop-operator"
